// Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

// Mod
archives_base_name=MineColonies_SoLCarrot
maven_group=steve_gall.minecolonies_solcarrot
mod_id=minecolonies_solcarrot
mod_version=1.3
mod_name=Spice of MineColonies Life: Carrot Flavor
mod_description=Spice of Life for MineColonies citizen.
mod_license=GPL 3.0
mod_homepage=https://legacy.curseforge.com/minecraft/mc-mods/minecolonies-sol-carrot
mod_source=https://github.com/gisellevonbingen-Minecraft/MineColonies_SoL_Carrot
mod_issues=https://github.com/gisellevonbingen-Minecraft/MineColonies_SoL_Carrot/issues

// Minecraft, Mod Loader
mc_version=1.21.1
neoforge_loader_version=4
neoforge_api_version=21.1.200
neoforge_api_version_range=[21.1.194,)

// Required
minecolonies_version=1.1.1232-1.21.1-snapshot
structurize_version=1.0.796-1.21.1-snapshot
multipiston_version=1.2.51-1.21.1-snapshot
blockui_version=1.0.199-1.21.1-snapshot
domumornamentum_version=1.0.223-snapshot
domumornamentum_file=7231908

// Optional
sol_carrot_file=5957429
tweaks_min_version=3.17

// Runtime Only
jei_version=19.19.6.235
jade_file=6155158
configured_file=5873783
farmers_delight_file=6154807
