// Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

// Mod
archives_base_name=MineColonies_SoLCarrot
maven_group=steve_gall.minecolonies_solcarrot
mod_id=minecolonies_solcarrot
mod_version=1.0
mod_name=Spice of MineColonies Life: Carrot Flavor
mod_description=Spice of Life for MineColonies citizen.
mod_license=GPL 3.0
mod_homepage=https://legacy.curseforge.com/minecraft/mc-mods/minecolonies-sol-carrot
mod_source=https://github.com/gisellevonbingen-Minecraft/MineColonies_SoL_Carrot
mod_issues=https://github.com/gisellevonbingen-Minecraft/MineColonies_SoL_Carrot/issues

// Minecraft, Mod Loader
mc_version=1.20.1
forge_loader_version=47
forge_api_version=47.2.0
forge_api_version_range=[47.1.13,)
mixin_version=0.8.5

// Required
minecolonies_version=1.20.1-1.1.827-snapshot
structurize_version=1.20.1-1.0.759-snapshot
multipiston_version=1.20-1.2.43-RELEASE
domumornamentum_version=1.20.1-1.0.186-RELEASE
blockui_version=1.20.1-1.0.156-RELEASE

// Optional
sol_carrot_file=4888575
tweaks_min_version=2.51

// Runtime Only
jei_version=15.2.0.23
jade_file=4573193
mekanism_version=10.4.0.14
configured_file=5180902
farmers_delight_file=5051242
